### ISSUE TITLE
Usage Instructions are confusing

### ISSUE THREAD

**Issue by cboulay** [Slicer/SlicerJupyter#45]
Under Option 2, I don't understand the purpose of bullets 3, 4, and 5. Why tell the user to install python and jupyter when ultimately it will be the Slicer-provided python interpreter and Slicer-provided jupyter kernel that are used?

I am raising this issue because after following the instructions I thought SlicerJupyter was using the environment I installed and was frustrated when it couldn't access my packages. If I now understand correctly, then these instructions are just a way to give the user a GUI to manage their notebooks. If the user already has a Python env with jupyter installed -- which is probably true for everyone interested in SlicerJupyter -- then couldn't they simply use that?

The command to install the kernel copied to clipboard can be changed to `{path_to_Slicer}/bin/PythonSlicer -m jupyter kernelspec install {...}` and the user can be told to run it from any console. This can appear earlier in the instructions.

Then the instructions to run the jupyter notebook server could be as simple as: "Run a jupyter notebook server from one of your other Python environments like Anaconda or Jupyter Lab. If you don't have another Python environment then use `./PythonSlicer -m jupyter notebook`" (except I couldn't get the latter to work! See below).

{And then continue with instructions on how to open a notebook with the correct kernel}

I admit my understanding of Python interpreters, jupyter kernels, jupyter notebook server and their interactions is rather basic. There's a good chance I'm misunderstanding how this is supposed to work.

--------------
I couldn't get `./PythonSlicer -m jupyter notebook` to work. It returned an esoteric error:

>File "/media/chad/STORE/Tools/Neurophys/Slicer-4.11.0-2020-06-06-linux-amd64/lib/Python/lib/python3.6/site-packages/prometheus_client/exposition.py", line 9, in <module>
>    from wsgiref.simple_server import make_server, WSGIServer, WSGIRequestHandler
>ModuleNotFoundError: No module named 'wsgiref.simple_server'

This returned no relevant search results. 'wsgiref.simple_server' is a core Python module so I'm guessing that PythonSlicer doesn't ship with a full set of modules. Maybe it should include the modules necessary to run jupyter server?

**Comment by lassoan** [comment]
Thanks for trying SlicerJupyter these and providing feedback. This is very useful.

> Under Option 2, I don't understand the purpose of bullets 3, 4, and 5. Why tell the user to install python and jupyter when ultimately it will be the Slicer-provided python interpreter and Slicer-provided jupyter kernel that are used?

If you anyone has ever used Jupyter on his computer then Jupyter is already set up and only a single kernel install command has to be executed (and pip install ipycanvas and ipevents for the interactive 3D renderer; if these have not been installed already). If this was not clear from the setup instructions then please send a pull request with some clarifications that you think would help users.

> The command to install the kernel copied to clipboard can be changed to {path_to_Slicer}/bin/PythonSlicer -m jupyter kernelspec install {...} and the user can be told to run it from any console. This can appear earlier in the instructions.

SlicerJupyter module creates the kernelspec file (by inserting the path of the Slicer launcher) when you start Slicer and open the module, so you need to install Slicer&SlicerJupyter before you can install the kernelspec, so I'm not sure how this could be simplified.

I haven't tried using Slicer's Python environment for running the Jupyter server, but the advantage would be that then SlicerJupyter could set up everything, so there would be no need for _any_ manual setup.

> I couldn't get ./PythonSlicer -m jupyter notebook to work. It returned an esoteric error
> This returned no relevant search results. 'wsgiref.simple_server' is a core Python module

Yes, this has been reported [here](https://github.com/Slicer/SlicerJupyter/issues/39), too, so we cannot run both the server and kernel from the same environment yet. This should not be hard to fix. I've added to [this](https://github.com/Slicer/Slicer/issues/4920) ticket.

---

For now we should clarify the installation instructions. I haven't even realized that not everyone is familiar with the independence of Jupyter server from the kernel, but since this confused both you and @pieper it means that it needs further explanation or simpler instructions.

After https://github.com/Slicer/SlicerJupyter/issues/39 is fixed, I'll add a "Launch Jupyter notebook" button to SlicerJupyter module. With a single button click, the module would install all prerequisites, set up everything, launch a Jupyter server, and open Jupyter in a browser.

**Comment by lassoan** [comment]
I've updated setup instructions, I hope they are more clear now. Pull request with further proposed changes are welcome.

Installing Jupyter server in Slicer's Python environment is tracked in https://github.com/Slicer/SlicerJupyter/issues/39.
