### ISSUE TITLE
Fix extension build on linux

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerJupyter#5]
On Linux platforms, `xeus` also requires `libuuid`, which is available in all linux distributions (`uuid-dev` on Debian). This package should be installed on factory machines.

**Comment by ihnorton** [comment]
@jcfr @sjh26 could you please add this package to the build system? There are other packaging issues on linux, which I can take care of, but I don't have any way to fix the build right now. I would like to make the mybinder image refresh automatically every few days, and the simplest way to do that is to use the existing SlicerPreview packages.

**Comment by jcfr** [comment]
For linux, it is a matter of updating this file: [Docker/qt5-centos7/Dockerfile](https://github.com/Slicer/SlicerBuildEnvironment/blob/master/Docker/qt5-centos7/Dockerfile). See https://github.com/Slicer/SlicerBuildEnvironment/pull/9  

That said, since `libuuid-devel` provides the shared library `libuuid.so`, should we package it or expect it to be available on every target system ? Installing `libuuid` could also be a prerequisite on linux.

```
$ sudo repoquery -l libuuid-devel
/usr/include/uuid
/usr/include/uuid/uuid.h
/usr/lib/libuuid.so
/usr/lib/pkgconfig/uuid.pc
/usr/share/doc/libuuid-devel-2.23.2
/usr/share/doc/libuuid-devel-2.23.2/COPYING
/usr/share/man/man3/uuid.3.gz
[...]
/usr/include/uuid
/usr/include/uuid/uuid.h
/usr/lib64/libuuid.so
/usr/lib64/pkgconfig/uuid.pc
/usr/share/doc/libuuid-devel-2.23.2
/usr/share/doc/libuuid-devel-2.23.2/COPYING
/usr/share/man/man3/uuid.3.gz
[...]
```

**Comment by ihnorton** [comment]
If we make it a prerequisite, we should put it on the main Slicer dep list rather than needing another specific step for SlicerJupyter.

Considering it is hard to get software installed on HPC-like systems, I would lean a bit towards packaging. It only links libc so it should be safe enough to redistribute (at least as safe as packaging libssl).

**Comment by ihnorton** [comment]
Looks like this is fixed?

http://slicer.cdash.org/index.php?project=SlicerPreview&date=2018-11-18&filtercount=1&showfilters=1&field1=label&compare1=63&value1=SlicerJupyter

(today's build [failed](http://slicer.cdash.org/index.php?project=SlicerPreview&date=2018-11-19&filtercount=1&showfilters=1&field1=label&compare1=63&value1=SlicerJupyter) but looks like it was just a network issue)

**Comment by lassoan** [comment]
Fixed.
