### ISSUE TITLE
Implement auto-complete

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerJupyter#7]
If user presses Tab key, auto-completion should be performed. Currently it just performs some hardcoded character replacement.

xSlicerInterpreter::complete_request_impl needs to be implemented properly. Probably the Python console needs to provide auto-complete feature, which this interpreter class can use.

**Comment by ihnorton** [comment]
Very WIP implementation using [jedi](https://github.com/davidhalter/jedi):

https://gist.github.com/ihnorton/bdb5104be634c04b38e5e218bb84fce4

![image](https://user-images.githubusercontent.com/327706/43422557-0935d28a-9418-11e8-9b1b-f2e9d413fde3.png)

The approach is
- pass the requested string-to-complete to a function defined *in python*, which then calls jedi, and returns a JSON string
- we pass the result back through xjson and return as usual

A couple issues/questions:

- are you ok with this approach, and the jedi dependency?

- I don't like the `__comp` temporary variable in the python namespace, but `pythonManager->executeString(...)` didn't work the way I expected (I thought I could say `res = pythonManager->executeString(...);` and directly get back the JSON string returned from the function, but `res.toStdString()` is always empty)

**Comment by lassoan** [comment]
Thanks a lot for working on this. Could you send a pull request, even if its WIP, so that we can easily test this?

Using jedi is not an issue, especially if it's a small library with no dependencies.
It might be confusing if auto-complete results are different from what you get in the embedded Python console in Slicer, but if the results are better then nobody will mind.

To get resturn value from executeString, I think you need to run it in _EvalInput_ mode - see example in this test: https://github.com/commontk/CTK/blob/cfbb46a772584e76e1bc0dee9be44008f2e6f943/Libs/Scripting/Python/Core/Testing/Cpp/ctkAbstractPythonManagerTest.cpp#L164-L173

**Comment by ihnorton** [comment]
Here's a working branch for now, but requires to manually install jedi (via pip).

https://github.com/ihnorton/SlicerJupyter/tree/auto_comp

That said, after playing with it a bit, I'm not sure yet if jedi is going to be a good approach. For example, I haven't figured out how to make it introspect wrapped extension code (https://github.com/davidhalter/jedi/issues/383), which would be a big limitation. I guess this is why IPython has their own supplementary completion logic on top of jedi (IPython completion works great).

> To get return value from executeString, I think you need to run it in EvalInput mode

Thanks, I ended up finding [this discussion](https://sourceforge.net/p/pythonqt/discussion/631393/thread/d25be296/), and using the `::call` approach which is nice because it takes arguments directly without string splicing.

**Comment by jcfr** [comment]
Currently working on a deadline, I will follow later this week with the code allowing to do the eval and return.

In a nutshell, the idea is to borrow the AST analysis code from ipython. And evaluate interactively only the last expression from the cell.

If needed, we could easily convert that part to C-api

**Comment by ihnorton** [comment]
> I will follow later this week with the code allowing to do the eval and return.

Thanks, got it already 😄 Andras' comment works, and `PythonQtObjectPtr::call` is what the branch is using now.

> In a nutshell, the idea is to borrow the AST analysis code from ipython. And evaluate interactively only the last expression from the cell.

IPython is switching to jedi, but apparently [there was a bug](https://github.com/ipython/ipython/pull/11076) in jedi where it neglected to look at __dir__. So probably on jedi master it will be ok. I'll check when I have a chance and update.

**Comment by lassoan** [comment]
Any luck with using Python packages? If not, then we could implement and use CTK console's auto-complete method (https://github.com/lassoan/CTK/blob/50885b9ed8af3cbdab12019594566e9d0dcfcc35/Libs/Widgets/ctkConsole.cpp#L1417).

**Comment by ihnorton** [comment]
Quick test of `jedi.Interpreter`: seems to work how I expect. I updated the branch linked above.

It completes everything under `slicer.`, `vtk.`, etc., but seems kind of slow for large namespaces (maybe few 100 ms lag for `vtk.`). I'm not yet sure if I'm using it correctly, and this is a debug build.

One useful thing to note: it actually does seem to do some partial evaluation (try `slicer.vtkMRMLScalarVolumeDisplayNode().` -- gives back the methods). I'm not sure how it is doing that, and so far in a few tests, it only goes one level deep. If we still want the fully nested partial-evaluation like CTK python console does, we may need to implement that separately (on top of jedi -- IPython and ptpython do both add layers to complete things like IPython magics and file paths).

> then we could implement and use CTK console's auto-complete method

I believe the CTK completer algorithm makes the simplifying assumption that input will only ever be a single line. That is not valid in the notebook cells, because the user may ask for a completion while at any line within a cell. So we probably do need more sophisticated parsing no matter what. I think jedi should be able to give us back the expression it is trying to complete, but I haven't figured out how to do that yet.

Side note:  if we use jedi, there are some exceptions listed here we may want to ignore: https://github.com/jonathanslenders/ptpython/blob/d00f8d454fe2b94c499869e6677cce7a22601fc4/ptpython/completer.py#L120-L160

(also note that you can copy the completion python code from the top `JupyterKernel/qSlicerJupyterKernelModule.cxx` to a cell and eval, then try tab-complete to test changes without rebuilding/restarting)

**Comment by lassoan** [comment]
Fixed by recent commit

**Comment by darekdev** [comment]
Probably it's slow, because of printing in command line.

**Comment by lassoan** [comment]
> Probably it's slow, because of printing in command line

I've also noticed this and disabled printing by default in my last commit.
