### ISSUE TITLE
Integration of jupyter slicer notebook in jupyterhub

### ISSUE THREAD

**Issue by bveeni** [Slicer/SlicerJupyter#74]
Hi everyone,
I am trying to have jupyter slicer notebook in Jupyterhub. For this, I created dockerfile which starts from jupyterhub image, where  I have installed all the required components of Jupyter slicer notebook and I am able to get "Slicer-4.13" in Notebook menu under new. However, when I try to create  new slicer notebook, the slicer kernel failed to start.
Is there anyone, who have successfully able to integrate this slicer notebook in Jupyterhub. 
Any sample dockerfile for this integration would be highly appreciated.
Thanks

**Comment by lassoan** [comment]
JupyterHub is used in binder (https://mybinder.org/v2/gh/Slicer/SlicerNotebooks/master). I would suspect that the problems is getting the display server set up, but you would need to get some logs to see how far the Slicer gets (does the Slicer process even started?) and see what goes wrong.

I'm closing this issue because it has been open for a long time, but feel free to reopen if you want to continue the discussion.
